server:
  port: 7051

spring:
  application:
    name: UniverseMonuments
  datasource:
    url: jdbc:oracle:thin:@//13.95.19.215:1521/dev
    username: um
    password: um
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.Oracle10gDialect

token:
  key:
    secret: B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdR
    expiration: 2
