server:
  port: 7050

spring:
  application:
    name: UniverseMonuments
  datasource:
    url: jdbc:oracle:thin:@//40.91.221.118:1521/dev
    username: um
    password: um
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      validation-timeout: 5000
      connection-test-query: select 1 from dual
      connection-timeout: 10000
      minimum-idle: 0
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
token:
  key:
    secret: B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdR
    expiration: 2
